source 'https://rubygems.org'
gem 'cocoapods',                # third party iOS libraries manager
    '0.34.0.rc2'                # 0.34 is not released yet, but required for xcode 6 support
gem 'pivotal_git_scripts'       # for git pair, which configures git authors when pair programming.
gem 'cocoapods-podfile_info'    # pod podfile-info shows list of used pods with description
