source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'KIF-Kiwi' do
    # even this target does not depend on any pods
    # we insert this dependency to workaround this cocoapods issue:  https://github.com/CocoaPods/CocoaPods/issues/2516
    pod "KIF-Kiwi", :path => "../KIF-Kiwi.podspec"
end

target 'Tests' do
    pod "KIF-Kiwi", :path => "../KIF-Kiwi.podspec"
end
