# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
script:
- export DEVICE_ID=`instruments -s devices | grep iPhone | sed 's/.*\[\(.*\)\].*/\1/p' | head -n 1`
- cd Example; xcodebuild test -workspace KIF-Kiwi.xcworkspace -scheme KIF-Kiwi -sdk iphonesimulator -destination "id=$DEVICE_ID"
